# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Social data analysis
tagline:          'A Jekyll theme'
description:      'This is a test webpage for the course'
url:              ""
baseurl:          ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

author:
  name:           'Zuzanna'


paginate:         5

# Custom vars
version:          2.1.0


